# Generated by Django 5.0.7 on 2024-07-13 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_paciente', models.CharField(blank=True, max_length=100, null=True)),
                ('n_registro', models.CharField(blank=True, max_length=15, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nome_do_pai', models.CharField(blank=True, max_length=100, null=True)),
                ('nome_da_mae', models.CharField(blank=True, max_length=100, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_saida', models.CharField(blank=True, max_length=100, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internaçao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_estabelecimento_solicitante', models.CharField(max_length=255)),
                ('cnes_solicitante', models.CharField(max_length=7)),
                ('nome_estabelecimento_executante', models.CharField(max_length=255)),
                ('cnes_executante', models.CharField(max_length=7)),
                ('cartao_nacional_saude', models.CharField(max_length=15)),
                ('raca', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('numero_prontuario', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_mae', models.CharField(max_length=255)),
                ('documento_identificacao', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=255)),
                ('municipio_residencia', models.CharField(max_length=100)),
                ('cod_ibge_municipio', models.CharField(max_length=7)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=15)),
                ('principais_sinais_sintomas_clinicos', models.TextField(blank=True, null=True)),
                ('condicoes_justificam_internacao', models.TextField(blank=True, null=True)),
                ('principais_resultados_exames', models.TextField(blank=True, null=True)),
                ('diagnostico_inicial', models.TextField(blank=True, null=True)),
                ('cid10_principal', models.CharField(max_length=10)),
                ('cid10_secundario', models.CharField(blank=True, max_length=10, null=True)),
                ('cid10_associadas', models.CharField(blank=True, max_length=10, null=True)),
                ('descricao_procedimento', models.TextField()),
                ('codigo_procedimento', models.CharField(max_length=10)),
                ('clinica', models.CharField(max_length=255)),
                ('carater_internacao', models.CharField(max_length=255)),
                ('documento_prof_solicitante', models.CharField(max_length=20)),
                ('cns_prof_solicitante', models.CharField(max_length=15)),
                ('cpf_prof_solicitante', models.CharField(max_length=11)),
                ('nome_profissional_solicitante', models.CharField(max_length=255)),
                ('data_solicitacao', models.DateField()),
                ('assinatura_medico', models.CharField(max_length=255)),
                ('acidente_transito', models.BooleanField(default=False)),
                ('acidente_trabalho_tipico', models.BooleanField(default=False)),
                ('acidente_trabalho_trajeto', models.BooleanField(default=False)),
                ('cnpj_seguradora', models.CharField(blank=True, max_length=14, null=True)),
                ('numero_bilhete', models.CharField(blank=True, max_length=20, null=True)),
                ('serie', models.CharField(blank=True, max_length=20, null=True)),
                ('cnpj_empresa', models.CharField(blank=True, max_length=14, null=True)),
                ('numero_bilhete_empresa', models.CharField(blank=True, max_length=20, null=True)),
                ('serie_empresa', models.CharField(blank=True, max_length=20, null=True)),
                ('emprego', models.BooleanField(default=False)),
                ('autonomo', models.BooleanField(default=False)),
                ('desempregado', models.BooleanField(default=False)),
                ('aposentado', models.BooleanField(default=False)),
                ('nao_segurado', models.BooleanField(default=False)),
                ('nome_profissional_autorizador', models.CharField(max_length=255)),
                ('cod_crm', models.CharField(max_length=20)),
                ('numero_autorizacao_internacao', models.CharField(max_length=20)),
                ('cns_autorizador', models.CharField(max_length=15)),
                ('cpf_autorizador', models.CharField(max_length=11)),
                ('data_autorizacao', models.DateField()),
                ('assinatura_carimbo', models.CharField(max_length=255)),
                ('assinatura_paciente_responsavel', models.CharField(max_length=255)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appClinica.paciente')),
            ],
            options={
                'verbose_name_plural': 'Internações',
            },
        ),
    ]
